language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./$SCRIPT
env:
  global:
  - PINS="dlm:."
  - SCRIPT=.travis-docker.sh
  matrix:
  - PACKAGE=dlm DISTRO="debian-unstable" OCAML_VERSION=4.04.2
  - PACKAGE=dlm DISTRO="debian-unstable" OCAML_VERSION=4.05.0
  - PACKAGE=dlm DISTRO="centos-7" OCAML_VERSION=4.02.3
branches:
  only: master
