name: Generate and upload docs

on:
  push:
    branches: master

jobs:
  ocaml:
    strategy:
      matrix:
        ocaml-compiler:
          - 4.12.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-doc

      - run: opam exec -- make doc

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/default/_doc/_html/
          publish_branch: gh-pages
